feat(engine): complete migu engine
UnblockNeteaseMusic/server-rust pull request #70
Opened 2022-01-17 16:08 UTC by memorydream

2022-01-17 16:14 UTC, memorydream commented on unm_resolver/src/engine/migu.rs
> +    //let reg_exp = Regex::new(r"\s*,\s*\").unwrap();
这边代码直接从nodejs版本那边抄的，感觉可以不用正则表达式
好像不分割歌手信息应该也行

2022-01-18 09:32 UTC, memorydream commented on unm_resolver/src/engine/migu.rs
> +    let enabled_flac = false;
这里，需要使用一个全局变量，但是我没有看到相关变量，先写个临时变量在这

2022-01-23 11:24 UTC, pan93412 requested changes

2022-01-23 11:24 UTC, pan93412 commented on unm_resolver/src/engine/migu.rs
> +    num.to_string().split('.').collect::<Vec<_>>()[1].to_string()
這裡建議這樣做：

```
num.to_string()
  .split('.')
  .skip(1).next() // 跳過第一個元素，取第二個元素。
  .ok_or(anyhow::anyhow!("not a valid number"))? // 如果沒有第二個元素就拋錯誤。
  .to_string() // 其餘同
```

效能比較高。

2022-01-23 11:24 UTC, pan93412 commented on unm_resolver/src/engine/migu.rs
> +    let urls = join_all(futures).await;
`join_all` 接受 Iterator，你可以不用先 `.collect`（可以提升效能）

2022-01-23 11:24 UTC, pan93412 commented on unm_resolver/src/engine/migu.rs
> +    }
```rust
let result = urls.find(|url| url.ok());
```

會更簡潔（而且也能給編譯器更大的優化空間）

2022-01-23 11:24 UTC, pan93412 commented on unm_resolver/src/engine/migu.rs
> +    //let reg_exp = Regex::new(r"\s*,\s*\").unwrap();
感覺可以 `.split(",")`

2022-01-23 11:24 UTC, pan93412 commented on unm_resolver/src/engine/migu.rs
> +        .ok_or(UnableToExtractJson("url", "string"))?;
盡量統一取索引的方式。

```rs
let format_type = response.pointer("/data/formatType").as_str().ok_or(...);
let url = response.pointer("/data/url").as_str().ok_or(...);
```

2022-01-23 11:24 UTC, pan93412 commented on unm_resolver/src/engine/migu.rs
> +    if format_type.eq(format) {
建議直接 `==`

2022-01-23 19:42 UTC, memorydream commented on unm_resolver/src/engine/migu.rs
> +    }
然而这么写会报错，我怎么样都没办法用类似的写法过编译

2022-01-23 19:50 UTC, memorydream commented on unm_resolver/src/engine/migu.rs
> +    num.to_string().split('.').collect::<Vec<_>>()[1].to_string()
这里不返回Result，不能用ok_or，没有其他写法的话这里不能改

2022-01-23 20:14 UTC, memorydream commented on unm_resolver/src/engine/migu.rs
> +
这里还有一个从外部获取的cookie，要怎么传进来？

2022-01-24 02:11 UTC, pan93412 commented on unm_resolver/src/engine/migu.rs
> +    }
> 然而这么写会报错，我怎么样都没办法用类似的写法过编译

```
let result = urls.find(|url| url.ok().is_some());
```

抱歉漏掉了 `is_some()`

2022-01-24 02:13 UTC, pan93412 commented on unm_resolver/src/engine/migu.rs
> +
你先放個 `FIXME`。我晚點會設計外部變數的傳入方式。

2022-01-24 02:17 UTC, pan93412 commented on unm_resolver/src/engine/migu.rs
> +    num.to_string().split('.').collect::<Vec<_>>()[1].to_string()
> 这里不返回Result，不能用ok_or，没有其他写法的话这里只能直接unwrap

你原本取下標的手法就會 panic（
回傳 Result 其實比較保險

2022-02-03 02:14 UTC, merged